import type { ApiUser, ApiConversation, Pagination } from "@/types/api";

const d = (daysAgo: number) =>
  new Date(Date.now() - daysAgo * 86_400_000).toISOString();

export const MOCK_USERS: ApiUser[] = [
  {
    id: "u-001",
    name: "Gabriel Bamiduro",
    email: "bamiduroeniolagabriel@gmail.com",
    role: "admin",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(30),
    createdAt: d(30),
    updatedAt: d(1),
  },
  {
    id: "u-002",
    name: "Amara Osei",
    email: "amara.osei@worknoon.io",
    role: "agent",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(20),
    createdAt: d(20),
    updatedAt: d(2),
  },
  {
    id: "u-003",
    name: "Lena Kovac",
    email: "lena.kovac@worknoon.io",
    role: "agent",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(18),
    createdAt: d(18),
    updatedAt: d(3),
  },
  {
    id: "u-004",
    name: "James Adeyemi",
    email: "jadeyemi@example.com",
    role: "merchant",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(14),
    createdAt: d(14),
    updatedAt: d(1),
  },
  {
    id: "u-005",
    name: "Sofia Reyes",
    email: "sofia.reyes@example.com",
    role: "designer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(12),
    createdAt: d(12),
    updatedAt: d(2),
  },
  {
    id: "u-006",
    name: "Kwame Boateng",
    email: "kwame.b@example.com",
    role: "customer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(10),
    createdAt: d(10),
    updatedAt: d(1),
  },
  {
    id: "u-007",
    name: "Nadia Petrov",
    email: "nadia.p@example.com",
    role: "customer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: d(8),
    createdAt: d(8),
    updatedAt: d(0),
  },
  {
    id: "u-008",
    name: "Tunde Fashola",
    email: "tunde.f@example.com",
    role: "merchant",
    avatarUrl: null,
    banned: true,
    emailVerifiedAt: d(6),
    createdAt: d(6),
    updatedAt: d(1),
  },
];

export const MOCK_USER_PAGINATION: Pagination = {
  page: 1,
  limit: 50,
  total: 8,
};

export const MOCK_CONVERSATIONS: ApiConversation[] = [
  {
    id: "conv-001",
    type: "support",
    status: "open",
    assignedAgentId: "u-002",
    participants: [{ userId: "u-006", readAt: d(0) }, { userId: "u-002", readAt: d(0) }],
    topic: "Order not received",
    productContext: { productId: "p-1", productName: "Wireless Headphones" },
    lastMessageId: "msg-001",
    lastMessageBody: "Can you check the tracking number?",
    lastMessageAt: d(0),
    createdAt: d(3),
    updatedAt: d(0),
  },
  {
    id: "conv-002",
    type: "direct",
    status: "assigned",
    assignedAgentId: "u-003",
    participants: [{ userId: "u-004", readAt: d(1) }, { userId: "u-003", readAt: d(0) }],
    topic: null,
    productContext: null,
    lastMessageId: "msg-002",
    lastMessageBody: "Got it, I'll look into that.",
    lastMessageAt: d(1),
    createdAt: d(5),
    updatedAt: d(1),
  },
  {
    id: "conv-003",
    type: "support",
    status: "resolved",
    assignedAgentId: "u-002",
    participants: [{ userId: "u-007", readAt: d(2) }, { userId: "u-002", readAt: d(2) }],
    topic: "Return request",
    productContext: { productId: "p-2", productName: "Leather Tote Bag" },
    lastMessageId: "msg-003",
    lastMessageBody: "Your return has been approved.",
    lastMessageAt: d(2),
    createdAt: d(7),
    updatedAt: d(2),
  },
  {
    id: "conv-004",
    type: "support",
    status: "escalated",
    assignedAgentId: null,
    participants: [{ userId: "u-005", readAt: null }, { userId: "u-003", readAt: d(1) }],
    topic: "Payment not reflecting",
    productContext: null,
    lastMessageId: "msg-004",
    lastMessageBody: "It's been 3 days and no update.",
    lastMessageAt: d(1),
    createdAt: d(4),
    updatedAt: d(1),
  },
  {
    id: "conv-005",
    type: "direct",
    status: "open",
    assignedAgentId: null,
    participants: [{ userId: "u-008", readAt: null }, { userId: "u-004", readAt: d(0) }],
    topic: null,
    productContext: { productId: "p-3", productName: "Running Shoes" },
    lastMessageId: "msg-005",
    lastMessageBody: "Do you have this in size 43?",
    lastMessageAt: d(0),
    createdAt: d(1),
    updatedAt: d(0),
  },
];

export const MOCK_CONVERSATION_PAGINATION: Pagination = {
  page: 1,
  limit: 50,
  total: 5,
};
