import type { ApiUser } from "@/types/api";

export type DirectoryEntry = ApiUser & {
  bio: string;
  location: string;
  ordersCompleted: number;
  conversationsCount: number;
};

export type DirectoryRole = "designer" | "merchant";

export const DIRECTORY_ENTRIES: DirectoryEntry[] = [
  {
    id: "mock-1",
    name: "Alice Johnson",
    email: "alice@example.com",
    role: "designer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Brand identity and digital product design. Clean, intentional work.",
    location: "Lagos, NG",
    ordersCompleted: 38,
    conversationsCount: 52,
  },
  {
    id: "mock-4",
    name: "Brandify Studio",
    email: "studio@brandify.com",
    role: "designer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Full-service creative studio. Strategy, identity, and visual systems.",
    location: "Abuja, NG",
    ordersCompleted: 61,
    conversationsCount: 89,
  },
  {
    id: "mock-2",
    name: "TechStore",
    email: "hello@techstore.com",
    role: "merchant",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Consumer electronics and accessories. Fast shipping, no hassle returns.",
    location: "Port Harcourt, NG",
    ordersCompleted: 124,
    conversationsCount: 207,
  },
  {
    id: "mock-5",
    name: "Urban Shop",
    email: "hello@urbanshop.com",
    role: "merchant",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Streetwear and lifestyle goods curated for modern taste.",
    location: "Lagos, NG",
    ordersCompleted: 88,
    conversationsCount: 113,
  },
  {
    id: "mock-8",
    name: "Zara Osei",
    email: "zara@example.com",
    role: "designer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Motion and UI designer. Bringing interfaces to life with purpose.",
    location: "Accra, GH",
    ordersCompleted: 22,
    conversationsCount: 31,
  },
  {
    id: "mock-9",
    name: "NovaMart",
    email: "hello@novamart.com",
    role: "merchant",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Home goods, kitchen, and decor. Trusted by over 2,000 customers.",
    location: "Kano, NG",
    ordersCompleted: 213,
    conversationsCount: 340,
  },
  {
    id: "mock-10",
    name: "Ike Design",
    email: "ike@ikedesign.com",
    role: "designer",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Packaging and print. Tactile design that stands on shelf.",
    location: "Enugu, NG",
    ordersCompleted: 17,
    conversationsCount: 24,
  },
  {
    id: "mock-11",
    name: "GreenLeaf Market",
    email: "info@greenleaf.com",
    role: "merchant",
    avatarUrl: null,
    banned: false,
    emailVerifiedAt: "",
    createdAt: "",
    updatedAt: "",
    bio: "Organic food and wellness products sourced from local farms.",
    location: "Ibadan, NG",
    ordersCompleted: 56,
    conversationsCount: 78,
  },
];

export const MOCK_DIRECTORY_PRESENCE: Record<string, "online" | "away" | "offline"> = {
  "mock-1":  "online",
  "mock-2":  "away",
  "mock-4":  "online",
  "mock-5":  "offline",
  "mock-8":  "online",
  "mock-9":  "away",
  "mock-10": "offline",
  "mock-11": "online",
};
